- name: "Composer | Check if composer is installed"
  stat:
    path: "{{ php.composer.path }}"
  register: composer_path

- name: "Composer | Setup Composer"
  block:
    - name: "Composer | Get Composer installer signature"
      uri:
        url: https://composer.github.io/installer.sig
        return_content: true
      register: composer_installer_signature

    - name: "Composer | Download Composer installer"
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-installer.php
        mode: 0755
        checksum: "sha384:{{ composer_installer_signature.content }}"

    - name: "Composer | Run Composer installer"
      command: >
        php composer-installer.php
        chdir=/tmp

    - name: "Composer | Remove composer-installer.php"
      file:
        path: /tmp/composer-installer.php
        state: absent
  when: not composer_path.stat.exists

- name: "Composer | Check if composer is installed"
  stat:
    path: /tmp/composer.phar
  register: temp_file

- name: "Composer | Set Composer globally"
  block:
    - name: "Composer | Move composer.phar to bin /user/bin"
      command: >
        mv /tmp/composer.phar /usr/bin/composer
        creates=/usr/bin/composer
    - name: "Composer | Remove composer.phar from temp folder"
      file:
        path: /tmp/composer.phar
        state: absent
  when: temp_file.stat.exists